language: cpp

compiler:
  - gcc

services:
  - memcached

before_script:
  - time TRAVIS=1 ./configure_generic.sh
# for some tests
  - time sudo locale-gen de_DE && sudo locale-gen zh_CN.utf8 && sudo locale-gen fr_FR
  - time make -j 16
  - cd hphp/test/zend/good/ext/curl/tests/responder && ../../../../../../../hhvm/hhvm -m server -p 8444 &
# mysql configuration for unit-tests
  - mysql -e 'CREATE DATABASE IF NOT EXISTS hhvm;'
  - export PDO_MYSQL_TEST_DSN="mysql:host=127.0.0.1;dbname=hhvm"
  - export PDO_MYSQL_TEST_USER="travis"
  - export PDO_MYSQL_TEST_PASS=""

# The larger test suites (slow, zend) take longer than 50 minutes to run. Since
# we have no way to change the timeout, we subdivide the jit/interp repo/normal
# matrix and then further split the large suites using an experimental cut
# which divides the number of tests in each sub-run roughly in two.
env:
  # non-repo
  - TEST_RUN_MODE="-m interp   quick"
    
script: time PHP_CURL_HTTP_REMOTE_SERVER="http://localhost:8444" hphp/hhvm/hhvm hphp/test/run $TEST_RUN_MODE

matrix:
  fast_finish: true
